version: "3.9"

services:
  java_apptest:
    container_name: java_apptest
    image: javacontruccion:1.0
    build:
      context: .
      target: java_build
    ports:
      - "9123:8085"
    restart: always
    networks:
      - apptestjava
  nginx_ssl_java_apptest:
    container_name: nginx_ssl_java_apptest
    build:
      context: .
      target: nginx_conf
    tty: true
    ports:
      - "9124:443"
    volumes:
      #- nginxfiles:/ssl/
      #- /home/app/nginx/html:/var/www/html
      #- /home/app/nginx/logs:/etc/nginx/logs
      - nginxfiles:/home/app/nginx
    #command: tail -f /dev/null
    command: > 
      bash -c "
        cp -r /home/app/nginx/html/ /var/www/html &&
        cp -r /home/app/nginx/logs/ /etc/nginx/logs &&
        cp -r /home/app/nginx/ssl/ /ssl/ && 
        tail -f /dev/null
      "
    restart: always
    depends_on:
      - java_apptest
    networks:
      - apptestjava

volumes:
  nginxfiles:
    external: true

  
networks:
  apptestjava:
    driver: bridge
